version: '3.3'

services:
 ftp:
  image: delfer/alpine-ftp-server
  ports:
   - '21:21'
   - '21000-21010:21000-21010'
  restart: always
  volumes:
   - ./ftp:/ftp/${FTP_USERNAME}
  environment:
   - USERS=${FTP_USERNAME}|${FTP_PASSWORD}
